version: "3.9"

services:
  # -----------------------------
  # API Python / FastAPI
  # -----------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-api
    command: sh -c "
      until pg_isready -h db -p 5432 -U ${DATABASE_USER} -d ${DATABASE_NAME} > /dev/null 2>&1; do
        echo 'Esperando o Postgres...';
        sleep 2;
      done;
      echo 'Banco pronto!';
      alembic upgrade head;
      uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT} --reload"
    working_dir: /app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      PYTHONPATH: /app
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  # -----------------------------
  # Postgres
  # -----------------------------
  db:
    image: postgres:15
    container_name: agent-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -q"]
      interval: 5s
      retries: 20
      timeout: 5s

  # -----------------------------
  # Redis
  # -----------------------------
  redis:
    image: redis:7
    container_name: agent-redis
    ports:
      - "${REDIS_PORT}:6379"

  # -----------------------------
  # Frontend Vue 3 (Dev / Hot Reload)
  # -----------------------------
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  pgdata:
