name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: desafio
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..10}; do
            pg_isready -h db -U postgres && break
            sleep 3
          done

      - name: Run migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/desafio

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/desafio